[build]
  command = "yarn build"
  publish = ".next"
  # Remove functions directory since we're not using it
  # functions = "netlify/functions"

  [build.environment]
    NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Disable secret scanning for this build
[build.processing]
  skip_processing = false

