[build]
  command = "yarn build"
  publish = ".next"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Disable secret scanning for this build
[build.processing]
  skip_processing = false

# Disable secret scanning
[build.environment]
  NETLIFY_DISABLE_SECRET_SCANNING = "true"
