[build]
  command = "npm run build"
  publish = "out"
  # Remove functions directory since we're not using it
  # functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Disable secret scanning for this build
[build.processing]
  skip_processing = false

# Configure secret scanning to ignore expected environment variables
[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  # Or use this to ignore specific keys:
  # SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_WIX_CLIENT_ID,NEXT_PUBLIC_SITE_URL"

# Wix redirect link handling
# Redirects payment links and other Wix-generated redirects to Wix's secure checkout
[[redirects]]
  from = "/_paylink/*"
  to = "https://secure.wix.com/checkout/purchase?token=:splat"
  status = 302
  force = true

# Generic redirect for other Wix redirect patterns (future-proofing)
[[redirects]]
  from = "/_checkout/*"
  to = "https://secure.wix.com/checkout/purchase?token=:splat"
  status = 302
  force = true

# Catch-all for any other underscore-prefixed paths that might be Wix redirects
[[redirects]]
  from = "/_*"
  to = "https://secure.wix.com/checkout/purchase?token=:splat"
  status = 302
  force = true
