[build]
  command = "npm run build"
  publish = ".next"
  # Remove functions directory since we're not using it
  # functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Disable secret scanning for this build
[build.processing]
  skip_processing = false

# Configure secret scanning to ignore expected environment variables
[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  # Or use this to ignore specific keys:
  # SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_WIX_CLIENT_ID,NEXT_PUBLIC_SITE_URL"
