export const constants = {
  phoneNumber: '+1 (204) 229-5871',
  companyName: 'ICANDO Movers',
  companyEmail: 'info@icandomovers.ca',
  companyAddress: '246 Hatcher Road',
  companyCity: 'Winnipeg',
  companyProvince: 'MB',
  companyPostalCode: 'R2C 3W7',
  companyCountry: 'Canada',
  companyWebsite: 'https://icandomovers.ca',
  companyLogo: '/custom/logo.svg',
  companyPhone: '+1 (204) 229-5871',
  instagram: 'http://www.instagram.com/icandomovers',
  facebook: 'https://www.facebook.com/icandomovers',
  websiteUrl: 'www.icandomovers.ca',
};
