import '@app/globals.css';
// import Footer from '@app/components/Layout/NavBarV2/Footer';
import { useServerAuthSession } from '@app/hooks/useServerAuthSession';
import PreloaderWrapper from '@app/components/Loader/PreloaderWrapper';
import React from 'react';

/**
 * Using force dynamic so changes in business assets (e.g. services) are immediately reflected.
 * If you prefer having it reflected only after redeploy (not recommended) please remove it
 * **/

export const revalidate = 0;

export default function RootLayout(layoutProps: any) {
  const { children } = layoutProps;
  const wixSession = useServerAuthSession();

  return (
    <html lang="en">
      <head>
        <title>Create Wix Bookings Site</title>
        <meta
          name="description"
          content="Generated by create next app with Wix Bookings integration"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.wix.com/favicon.ico" />
      </head>
      {wixSession.wixClient ? (
        <body
          className="parallax-background"
          style={{ backgroundColor: '#F5F5F5' }}
        >
          <PreloaderWrapper>{children}</PreloaderWrapper>
          {/* <Footer /> */}
        </body>
      ) : (
        <body className="">
          <main className="max-w-full-content mx-auto bg-gray-c2 pt-32">
            <h1>
              Page not available. Please add an environment variable called
              NEXT_PUBLIC_WIX_CLIENT_ID, containing the client ID, to your
              deployment provider.
            </h1>
          </main>
        </body>
      )}
    </html>
  );
}
